CREATE TABLE CLIENTE(

	ID_CLIENTE	SERIAL NOT NULL,
	NOME		VARCHAR(49) NOT NULL,
	LOGIN		VARCHAR(10) NOT NULL,
	SENHA		VARCHAR(11) NOT NULL,

	CONSTRAINT pk_idcliente PRIMARY KEY (ID_CLIENTE)

);


CREATE TABLE EVENTO(

	ID_EVENTO	SERIAL NOT NULL,
	DATA		DATE NOT NULL,
	CATEGORIA	VARCHAR(40) NOT NULL,
	LOCAL		VARCHAR(50) NOT NULL,
	TIPO		VARCHAR(20) NOT NULL,

	CONSTRAINT pk_idevento PRIMARY KEY (ID_EVENTO)
	
);

CREATE TABLE MATERIAL(

	ID_MATERIAL	SERIAL NOT NULL,
	NOME		VARCHAR(30) NOT NULL,
	QUALIDADE	VARCHAR(30) NOT NULL,
	PRECO		DECIMAL NOT NULL,

	CONSTRAINT pk_idmaterial PRIMARY KEY (ID_MATERIAL)
	
);


CREATE TABLE FUNCIONARIO(

	ID_FUNCIONARIO	SERIAL NOT NULL,
	CPF		VARCHAR(14) NOT NULL,
	NOME		VARCHAR(30) NOT NULL,
	LOGIN		VARCHAR(20) NOT NULL,
	SENHA		VARCHAR(10) NOT NULL,
	SEXO		CHAR(2) NOT NULL,

	CONSTRAINT pk_idfuncionario PRIMARY KEY (ID_FUNCIONARIO)
	
);